server:
  port: 8081
logging:
  level:
    com.example: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
management:
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4320}
  endpoint:
    prometheus:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    baggage:
      enabled: false
    propagation:
      type: w3c
grpc:
  server:
    port: 9091
  client:
    hello:
      address: localhost:9090
      negotiation-type: plaintext
spring:
  application:
    name: service-b
    version: 1.0.0
