version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    depends_on:
      - fluentd
    networks:
      - elk
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.kafka
    depends_on:
      - zookeeper
      - fluentd
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - elk
  postgres:
    image: postgres:15
    container_name: postgres_db
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456A@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - fluentd
    restart: unless-stopped
    networks:
      - elk
  service-a:
    image: service-a:latest
    container_name: service-a
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.service-a
    depends_on:
      - postgres
      - kafka
      - zipkin
      - jaeger
      - fluentd
    ports:
      - "8089:8089"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123456A@
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      MANAGEMENT_JAEGER_TRACING_ENDPOINT: http://jaeger:14250
    restart: unless-stopped
    networks:
      - elk
  service-b:
    image: service-b:latest
    container_name: service-b
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.service-b
        fluentd-async: "true"
    depends_on:
      - service-a
      - zipkin
      - jaeger
      - fluentd
    ports:
      - "8081:8081"
      - "9091:9091"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces  # Internal port
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      GRPC_CLIENT_HELLO_ADDRESS: service-a:9090
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      MANAGEMENT_JAEGER_TRACING_ENDPOINT: http://jaeger:14250
    restart: unless-stopped
    networks:
      - elk
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.zipkin
        fluentd-async: "true"
    ports:
      - "9411:9411"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx128m
    depends_on:
      - fluentd
    networks:
      - elk
  #  jaeger:
  #      image: jaegertracing/all-in-one:1.52
  #      container_name: jaeger
  #      logging:
  #        driver: fluentd
  #        options:
  #          fluentd-address: localhost:24224
  #          tag: docker.jaeger
  #          fluentd-async: "true"
  #      ports:
  #        - "16686:16686"  # UI
  #        - "14250:14250"  # Model v2 endpoint
  #        - "4317:4317"    # OTLP gRPC
  #        - "4318:4318"    # OTLP HTTP
  #        - "14268:14268"  # Jaeger HTTP thrift
  #        - "14269:14269"  # Admin port
  #        - "6831:6831/udp" # Jaeger thrift compact (UDP)
  #        - "6832:6832/udp"
  #      environment:
  #        - SPAN_STORAGE_TYPE=elasticsearch
  #        - ES_SERVER_URLS=http://elasticsearch:9200
  #        - ES_USERNAME=admin01           # Referencing environment variable for username
  #        - ES_PASSWORD=123456aA@
  #        - ES_TAGS_AS_FIELDS_ALL=true
  #        - ES_NUM_SHARDS=1
  #        - ES_NUM_REPLICAS=0
  #        - COLLECTOR_OTLP_ENABLED=true
  #        - METRICS_STORAGE_TYPE=prometheus
  #        - PROMETHEUS_HTTP_ROUTE=/metrics
  #        - LOG_LEVEL=debug
  #        - METRICS_BACKEND=prometheus
  #        - PROMETHEUS_SERVER_URL=http://prometheus:9090
  #        - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
  #        - PROMETHEUS_QUERY_NAMESPACE=span_metrics
  #        - PROMETHEUS_QUERY_DURATION_UNIT=ms
  #        - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
  #        - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
  #      depends_on:
  #        - fluentd
  #        - prometheus
  #      volumes:
  #        - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
  #      command:
  #          - "--query.ui-config=/etc/jaeger/jaeger-ui.json"
  #      networks:
  #        - elk
  jaeger:
    image: jaegertracing/jaeger
    container_name: jaeger
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json" # Do we need this for v2 ? Seems to be running without this.
      - "./config-spm.yaml:/etc/jaeger/config.yml"
    command: [ "--config", "/etc/jaeger/config.yml" ]
    ports:
      - "16686:16686"
      - "14269:14269"
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    networks:
      - elk
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    #    logging:
    #      driver: fluentd
    #      options:
    #        fluentd-address: localhost:24224
    #        tag: docker.elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=admin01
      - ELASTIC_PASSWORD=123456aA@
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    depends_on:
      - fluentd
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin02
      - ELASTICSEARCH_PASSWORD=123456aA@
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - fluentd
    networks:
      - elk
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.15.0
    container_name: apm-server
    ports:
      - "8200:8200"
    environment:
      - ELASTIC_APM_SECRET_TOKEN=fzd4MJLyPLSXZ0oUj7-hzPrtxGC8rKHhTbMKO6wVThVcRib8w5r4Jdt00BzAX-UT-shurF0vtQJLeK3qMqRnPA
    command: >
      apm-server -e
        -E apm-server.auth.secret_token=fzd4MJLyPLSXZ0oUj7-hzPrtxGC8rKHhTbMKO6wVThVcRib8w5r4Jdt00BzAX-UT-shurF0vtQJLeK3qMqRnPA
        -E apm-server.rum.enabled=true
        -E apm-server.rum.allow_origins=['*']
        -E setup.kibana.host=host.docker.internal:5601
        -E setup.kibana.username=admin03
        -E setup.kibana.password=123456aA@
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E apm-server.kibana.username=admin03
        -E apm-server.kibana.password=123456aA@
        -E output.elasticsearch.hosts=["host.docker.internal:9200"]
        -E output.elasticsearch.username=admin01
        -E output.elasticsearch.password=123456aA@
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8200/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  fluentd:
    build: fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - /var/log:/var/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elk
  kong:
    image: kong:3.8
    user: root
    container_name: kong
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.kong
        fluentd-async: "true"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_LOG_LEVEL: info
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_TRACING_INSTRUMENTATIONS: "all"
      KONG_TRACING: "on"
      KONG_TRACING_SAMPLING_RATE: "1.0"
      KONG_TRACING_TYPE: "opentelemetry"
      KONG_NGINX_HTTP_LOG_FORMAT: >-
        my_custom_format '$$remote_addr - [$$time_local]
        "$$request" $$status $$body_bytes_sent
        "$$http_referer" "$$http_user_agent"
        rt=$$request_time uct="$$upstream_connect_time" uht="$$upstream_header_time" urt="$$upstream_response_time"'
      KONG_PROXY_ACCESS_LOG: /dev/stdout my_custom_format
      KONG_TRUSTED_IPS: "0.0.0.0/0,::/0"
      KONG_REAL_IP_HEADER: "X-Forwarded-For"
      KONG_REAL_IP_RECURSIVE: "on"
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    depends_on:
      - fluentd
    networks:
      - elk
  prometheus:
    image: prom/prometheus:v3.6.0@sha256:76947e7ef22f8a698fc638f706685909be425dbe09bd7a2cd7aca849f79b5f64
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--log.level=debug'    # Bật log debug
      - '--log.format=json'
    networks:
      - elk

volumes:
  postgres_data:
  elasticsearch_data:
  prometheus_data:
networks:
  elk:
    driver: bridge
