global:
  scrape_interval: 15s
scrape_configs:
  # Jaeger tracing
  - job_name: 'jaeger'
    static_configs:
      - targets: ['host.docker.internal:14269']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Spring Boot applications
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'service-a:8089'
          - 'service-b:8081'
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    params:
      format: ['prometheus']

